# Generated by Django 4.1.7 on 2023-03-31 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Названия')),
                ('ParentName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'doch',
                'verbose_name_plural': 'Дочерная-Категория',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('contact', models.IntegerField(verbose_name='Контакт: (+998)')),
                ('location', models.CharField(max_length=256, verbose_name='Адресс')),
                ('ChatId', models.IntegerField(verbose_name='ID-чата')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Couriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='Имя')),
                ('contact', models.IntegerField(verbose_name='Контакт: (+998)')),
            ],
            options={
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('debt', models.FloatField(verbose_name='Долг')),
            ],
            options={
                'verbose_name_plural': 'Заведение',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientId', models.IntegerField(verbose_name='ID-клиента')),
                ('place', models.CharField(max_length=255, verbose_name='Адресс')),
                ('courier', models.CharField(max_length=60, verbose_name='Курьер')),
                ('status', models.CharField(max_length=60, verbose_name='Статус')),
                ('order_price', models.IntegerField(verbose_name='Стоимость заказа')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('type', models.CharField(choices=[('1-Dona', '1-Dona'), ('Kg', 'Kg'), ('Ltr', 'Ltr'), ('blok', 'blok')], max_length=100, verbose_name='Тип')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Картина')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
