# Generated by Django 4.1.7 on 2023-03-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ichimlik', 'ichimlik'), ('oziq-ovqat', 'oziq-ovqat'), ('shirinlik', 'shirinlik'), ('sut-maxsulotlari', 'sut-maxsulotlari')], max_length=100)),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('1-Dona', '1-Dona'), ('Kg', 'Kg'), ('Ltr', 'Ltr'), ('blok', 'blok')], max_length=100)),
            ],
        ),
    ]
