# Generated by Django 4.1.7 on 2023-03-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
