# Generated by Django 4.1.7 on 2023-03-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Названия')),
            ],
            options={
                'verbose_name_plural': ' Родительская-Категория',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('contact', models.IntegerField(verbose_name='Контакт: (+998)')),
                ('location', models.CharField(max_length=256, verbose_name='Адресс')),
                ('ChatId', models.IntegerField(verbose_name='ID-чата')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Couriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='Имя')),
                ('contact', models.IntegerField(verbose_name='Контакт: (+998)')),
            ],
            options={
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('debt', models.FloatField(verbose_name='Долг')),
            ],
            options={
                'verbose_name_plural': 'Заведение',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientId', models.IntegerField(verbose_name='ID-клиента')),
                ('place', models.CharField(max_length=255, verbose_name='Адресс')),
                ('courier', models.CharField(max_length=60, verbose_name='Курьер')),
                ('status', models.CharField(max_length=60, verbose_name='Статус')),
                ('order_price', models.IntegerField(verbose_name='Стоимость заказа')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='foods',
            name='category',
        ),
        migrations.AddField(
            model_name='foods',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Картина'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Названия'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='type',
            field=models.CharField(choices=[('1-Dona', '1-Dona'), ('Kg', 'Kg'), ('Ltr', 'Ltr'), ('blok', 'blok')], max_length=100, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Названия')),
                ('ParentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.allcategories', verbose_name='Родитель')),
            ],
            options={
                'verbose_name_plural': 'Дочерная-Категория',
            },
        ),
    ]
