# Generated by Django 4.1.7 on 2023-04-04 18:02

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_shoppinglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.AddField(
            model_name='foods',
            name='items',
            field=django_jsonform.models.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
