# Generated by Django 4.1.7 on 2023-03-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_foods_options_alter_foods_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='№')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('debt', models.FloatField(verbose_name='Долг')),
            ],
            options={
                'verbose_name_plural': 'Заведение',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='№')),
                ('place', models.CharField(max_length=255)),
                ('courier', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='foods',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Картина'),
        ),
    ]
