# Generated by Django 4.1.7 on 2023-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_merchant_orders_alter_foods_options_alter_foods_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
