# Generated by Django 4.1.7 on 2023-04-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_excelimport_alter_category_options_alter_foods_items_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelImport',
        ),
    ]
