# Generated by Django 4.1.7 on 2023-04-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_delete_excelimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
    ]
